const sidToUser = new Map(); // this is a hash map to store the users and their session ids

// id -> generated by uuidv4(), user -> findOne({email,name}) (that has tried to log in)
function setuser(id,user)
{
    sidToUser.set(id,user);
}

function getuser(id)
{
    return sidToUser.get(id);
}

module.exports=
{
    getuser,
    setuser
}